FEATURE: add option to show previous and next links
Flowpack/Flowpack.Listable pull request #39
Opened 2020-04-06 19:42 UTC by andrehoffmann30

In this PR I added the option to show previous and next links for a better user experience.

2020-04-06 20:21 UTC, daniellienert requested changes
Hey @andrehoffmann30, 
looks great!
Would you please add your configuration option also to the readme.

2020-04-06 20:21 UTC, daniellienert commented on Classes/Fusion/PaginationArrayImplementation.php
> +        $showPreviousNextLinks = $this->fusionValue('showPreviousNextLinks');
```suggestion
        $showPreviousNextLinks = (bool)$this->fusionValue('showPreviousNextLinks');
```

2020-04-06 20:21 UTC, daniellienert commented on Classes/Fusion/PaginationArrayImplementation.php
> +    public function evaluate()
```suggestion
    public function evaluate(): array
```

2020-04-06 20:38 UTC, andrehoffmann30 commented on Classes/Fusion/PaginationArrayImplementation.php
> +        $showPreviousNextLinks = $this->fusionValue('showPreviousNextLinks');
I added your suggestions.

2020-04-06 20:39 UTC, andrehoffmann30 commented on Classes/Fusion/PaginationArrayImplementation.php
> +    public function evaluate()
I added your suggestion.

2020-04-07 07:23 UTC, daniellienert approved these changes

2020-04-07 07:23 UTC, merged